# Generated by Django 3.2.9 on 2021-11-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureGlam', '0002_result_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_no', models.IntegerField(default=0)),
                ('t_name', models.CharField(default='', max_length=255)),
                ('t_type', models.CharField(default='', max_length=255)),
                ('t_question', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
