# Generated by Django 3.2.9 on 2021-11-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureGlam', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='t_answer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
