# Generated by Django 3.2.9 on 2021-11-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureGlam', '0004_test_t_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
