# Generated by Django 3.2.9 on 2021-12-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureGlam', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='option1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='option2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='option3',
            field=models.CharField(default='', max_length=255),
        ),
    ]
