# Generated by Django 3.2.9 on 2021-12-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureGlam', '0006_auto_20211201_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='t_no',
        ),
    ]
