# Generated by Django 3.2.9 on 2021-12-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureGlam', '0008_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='t_answer',
            new_name='tanswer',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='t_name',
            new_name='tname',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='t_question',
            new_name='tquestion',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='t_type',
            new_name='ttype',
        ),
    ]
