# Generated by Django 3.2.9 on 2021-12-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureGlam', '0009_auto_20211201_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
