# Generated by Django 3.2.9 on 2021-12-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureGlam', '0010_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
