# Generated by Django 3.2.9 on 2021-12-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureGlam', '0011_alter_test_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
