# Generated by Django 3.2.9 on 2021-12-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureGlam', '0013_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tid',
            field=models.IntegerField(default='', max_length=20, null=True),
        ),
    ]
