# Generated by Django 3.2.9 on 2021-12-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureGlam', '0015_alter_test_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='tid',
            field=models.IntegerField(default='0', max_length=20),
        ),
    ]
